spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_category_service
    username: root
    password: yerevan21


  liquibase:
    change-log: classpath:db/changelog/migration.xml

server:
  servlet:
    context-path: /api/v1

jwt:
  secret: k2y75xxx
  expiration: 330000
